version: '3.9'
services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    volumes:
      - ./backend/:/app
    command: npm run start:dev
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      PORT: 8080
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    env_file:
      - .env
    volumes:
      - ./postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
