version: '3.9'
services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    volumes:
      - ./backend/:/app
    command: npm i && npm run start:dev
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
      PORT: 8080
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=password"
    volumes:
      - ./backend/configs/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./backend/postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
